name = input("What is the name of the patient?")
age = input("Enter age in years")
weight = input("Enter weight(kg)")
height = input("height(meters)")
heart_rate = input("heart rate?")
temperature = input("tempearture?")

print("===== PATIENT SUMMARY =====")
print("Name:", name)
print("Age:", age, "years")
print("Weight:", weight, "kg")
print("Height:", height, "m")
print("Heart Rate:", heart_rate, "bpm")
print("Temperature:", temperature, "°C")
